# Generated by Django 2.0.5 on 2018-05-22 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('exterior_color', models.CharField(max_length=100)),
                ('wheels', models.CharField(max_length=100)),
                ('interior_package', models.CharField(max_length=100)),
                ('audio_system', models.CharField(max_length=100)),
                ('date_quoted', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
