# Generated by Django 2.0.5 on 2018-05-23 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclequote',
            old_name='date_quoted',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='vehiclequote',
            name='audio_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_quotes', to='product_vehicle.AudioSound'),
        ),
        migrations.AlterField(
            model_name='vehiclequote',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_quotes', to='product_vehicle.Engine'),
        ),
        migrations.AlterField(
            model_name='vehiclequote',
            name='exterior_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_quotes', to='product_vehicle.ExteriorColor'),
        ),
        migrations.AlterField(
            model_name='vehiclequote',
            name='interior_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_quotes', to='product_vehicle.InteriorColor'),
        ),
        migrations.AlterField(
            model_name='vehiclequote',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_quotes', to='product_vehicle.Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehiclequote',
            name='wheels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_quotes', to='product_vehicle.Wheel'),
        ),
    ]
