# Generated by Django 2.0.5 on 2018-05-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_vehicle', '0002_auto_20180523_0127'),
        ('vehicle_quote', '0002_auto_20180523_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclequote',
            name='audio_system',
        ),
        migrations.AddField(
            model_name='vehiclequote',
            name='audio_system',
            field=models.ManyToManyField(related_name='vehicle_quotes', to='product_vehicle.AudioSound'),
        ),
        migrations.RemoveField(
            model_name='vehiclequote',
            name='engine',
        ),
        migrations.AddField(
            model_name='vehiclequote',
            name='engine',
            field=models.ManyToManyField(related_name='vehicle_quotes', to='product_vehicle.Engine'),
        ),
        migrations.RemoveField(
            model_name='vehiclequote',
            name='exterior_color',
        ),
        migrations.AddField(
            model_name='vehiclequote',
            name='exterior_color',
            field=models.ManyToManyField(related_name='vehicle_quotes', to='product_vehicle.ExteriorColor'),
        ),
        migrations.RemoveField(
            model_name='vehiclequote',
            name='interior_package',
        ),
        migrations.AddField(
            model_name='vehiclequote',
            name='interior_package',
            field=models.ManyToManyField(related_name='vehicle_quotes', to='product_vehicle.InteriorColor'),
        ),
        migrations.RemoveField(
            model_name='vehiclequote',
            name='model_name',
        ),
        migrations.AddField(
            model_name='vehiclequote',
            name='model_name',
            field=models.ManyToManyField(related_name='vehicle_quotes', to='product_vehicle.Vehicle'),
        ),
        migrations.RemoveField(
            model_name='vehiclequote',
            name='wheels',
        ),
        migrations.AddField(
            model_name='vehiclequote',
            name='wheels',
            field=models.ManyToManyField(related_name='vehicle_quotes', to='product_vehicle.Wheel'),
        ),
    ]
