# Generated by Django 2.0.5 on 2018-05-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_quote', '0004_auto_20180523_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclequote',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
