# Generated by Django 2.0.5 on 2018-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_quote', '0004_auto_20180523_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclequote',
            name='cost',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclequote',
            name='list_price',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
