# Generated by Django 2.0.5 on 2018-05-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_quote', '0006_auto_20180523_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclequote',
            name='manufacture_cost',
            field=models.FloatField(null=True),
        ),
    ]
