# Generated by Django 2.0.5 on 2018-05-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
