# Generated by Django 2.0.5 on 2018-05-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_vehicle', '0002_auto_20180523_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cost',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
