# Generated by Django 2.0.5 on 2018-05-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_vehicle', '0003_auto_20180523_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='multiplier',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_cost',
            field=models.FloatField(default=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='markup_multiplier',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiosound',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='engine',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exteriorcolor',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='interiorcolor',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='cost',
            field=models.FloatField(),
        ),
    ]
