# Generated by Django 2.0.5 on 2018-05-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_vehicle', '0002_auto_20180522_2155'),
        ('product_vehicle', '0004_auto_20180523_1839'),
    ]

    operations = [
    ]
